### ISSUE TITLE
no such file or directory : `newtest.py`

### ISSUE THREAD

**Issue by yani-rl-ai** [mymultiverse/GeneticAlgo_OpenAIGymCartPole#1]
Hi @mymultiverse, thank you for sharing this code.
i am a newbie at openAI gym.
i got this following error : 
python genetic_cartpole.py
generation: 1, score: 47.0
generation: 2, score: 121.0
generation: 3, score: 121.0
generation: 4, score: 106.0
generation: 5, score: 241.0
generation: 6, score: 189.0
generation: 7, score: 216.0
generation: 8, score: 288.0
generation: 9, score: 277.0
generation: 10, score: 264.0
('Average accepted score:', 187.0)
('Median score for accepted scores:', 202.5)
Traceback (most recent call last):
  File "genetic_cartpole.py", line 248, in <module>
    param = np.load("newtest.npy")
  File "/home/kubotalab/anaconda3/envs/gymenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 422, in load
    fid = open(os_fspath(file), "rb")
IOError: [Errno 2] No such file or directory: 'newtest.npy'

please kindly help me

**Comment by mymultiverse** [comment]
@ROSNovice As it says in line 248.  Change it 
 `param = np.load("newtest.npy") to param = np.load("savedmodel.npy")`

**Comment by yani-rl-ai** [comment]
thanks for your reply,
bu i got a new error
rtPole$ python genetic_cartpole.py
generation: 1, score: 11.0
generation: 2, score: 10.0
generation: 3, score: 11.0
generation: 4, score: 11.0
generation: 5, score: 11.0
generation: 6, score: 10.0
generation: 7, score: 10.0
generation: 8, score: 10.0
generation: 9, score: 10.0
generation: 10, score: 10.0
generation: 11, score: 11.0
generation: 12, score: 10.0
generation: 13, score: 10.0
generation: 14, score: 10.0
generation: 15, score: 11.0
generation: 16, score: 11.0
generation: 17, score: 10.0
generation: 18, score: 10.0
generation: 19, score: 10.0
generation: 20, score: 10.0
('Average accepted score:', 10.35)
('Median score for accepted scores:', 10.0)
Traceback (most recent call last):
  File "genetic_cartpole.py", line 248, in <module>
    param = np.load("savedmodel.npy")
  File "/home/kubotalab/anaconda3/envs/GA27/lib/python2.7/site-packages/numpy/lib/npyio.py", line 447, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/kubotalab/anaconda3/envs/GA27/lib/python2.7/site-packages/numpy/lib/format.py", line 696, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False

**Comment by yani-rl-ai** [comment]
i tried to downgrade the numpy version, but i get this following error 
~/Genetic_Algorithm OpenAIgym/GeneticAlgo_OpenAIGymCartPole$ python genetic_cartpole.py
generation: 1, score: 11.0
generation: 2, score: 11.0
generation: 3, score: 10.0
generation: 4, score: 11.0
generation: 5, score: 11.0
generation: 6, score: 10.0
generation: 7, score: 10.0
generation: 8, score: 10.0
generation: 9, score: 10.0
generation: 10, score: 10.0
generation: 11, score: 10.0
generation: 12, score: 10.0
generation: 13, score: 10.0
generation: 14, score: 16.0
generation: 15, score: 14.0
generation: 16, score: 16.0
generation: 17, score: 16.0
generation: 18, score: 17.0
generation: 19, score: 16.0
generation: 20, score: 15.0
('Average accepted score:', 12.2)
('Median score for accepted scores:', 11.0)
Traceback (most recent call last):
  File "genetic_cartpole.py", line 271, in <module>
    print test_run_env(env, in_w, in_b, hid_w,out_w)
  File "genetic_cartpole.py", line 262, in test_run_env
    action = nn(obs,in_w,in_b,hid_w,out_w)
  File "genetic_cartpole.py", line 84, in nn
    out_put = out_put.argsort().reshape(1,adim)
ValueError: cannot reshape array of size 1 into shape (1,2)
